export const LAYER_REGISTRY = [
  // ── Archaeology & Sites ──────────────────────────────────────────────────
  {
    id: 'sites',
    group: 'Archaeology & Sites',
    label: 'Archaeological Sites',
    color: '#e85d04',
    mapboxType: 'circle',
    dataUrl: './data/sites.geojson',
    visible: true,
    description: 'Known sites sourced from Pleiades and Wikidata',
    sourceUrl: 'https://pleiades.stoa.org/',
  },
  {
    id: 'maya-inscriptions',
    group: 'Archaeology & Sites',
        label: 'Maya Inscription Sites',
    color: '#0077b6',
    mapboxType: 'circle',
    dataUrl: './data/maya-inscriptions.geojson',
    visible: false,
    description: '314 sites with recorded Maya inscriptions (Kaggle / ujwalkandi)',
    sourceUrl: 'https://www.kaggle.com/datasets/ujwalkandi/maya-inscriptions',
  },
  {
    id: 'inah-archaeological-zones',
    group: 'Archaeology & Sites',
        label: 'INAH Archaeological Zones (Mexico)',
    color: '#b5451b',
    mapboxType: 'circle',
    dataUrl: './data/inah-archaeological-zones.geojson',
    visible: false,
    description: '494 officially open pre-Hispanic zones in Mexico (INAH / Wikidata)',
    sourceUrl: 'https://www.wikidata.org/',
  },
  {
    id: 'unesco-world-heritage',
    group: 'Archaeology & Sites',
        label: 'UNESCO World Heritage Sites',
    color: '#1565c0',
    mapboxType: 'circle',
    dataUrl: './data/unesco-world-heritage.geojson',
    visible: false,
    description: '50 WHC sites in Mesoamerica — UNESCO DataHub (open access)',
    sourceUrl: 'https://whc.unesco.org/en/list/',
  },
  {
    id: 'lidar-surveys-opentopography',
    group: 'Archaeology & Sites',
        label: 'Open LiDAR Surveys (OpenTopography)',
    color: '#7b1fa2',
    mapboxType: 'circle',
    dataUrl: './data/lidar-surveys-opentopography.geojson',
    visible: false,
    description: '4 publicly archived archaeological LiDAR surveys — OpenTopography / NSF (CC-BY)',
    sourceUrl: 'https://opentopography.org/catalog',
  },

  // ── Empires & Culture ────────────────────────────────────────────────────
  {
    id: 'classical-empires',
    group: 'Empires & Culture',
        label: 'Classical Empires',
    color: '#7b2d8b',
    mapboxType: 'fill',
    featureColor: true,
    colorBy: 'name',
    colorLegend: [
      { label: 'Mayan',       value: 'Mayan',       color: '#4a6fd4' },
      { label: 'Teotihuacan', value: 'Teotihuacan', color: '#d4813a' },
      { label: 'Zapotec',     value: 'Zapotec',     color: '#3d9e52' },
    ],
    dataUrl: './data/classical-empires.geojson',
    visible: false,
    description: 'Teotihuacan, Zapotec, Maya and others (~100 BCE–900 CE)',
    sourceUrl: null,
  },
  {
    id: 'postclassical-empires',
    group: 'Empires & Culture',
        label: 'Post-Classical Empires',
    color: '#c2185b',
    mapboxType: 'fill',
    featureColor: true,
    colorBy: 'name',
    colorLegend: [
      { label: 'Aztec (Nahuatl)',        value: 'Aztec (Nahuatl)',        color: '#c55d29' },
      { label: 'Tarascan (Purepecha)',    value: 'Tarascan (Purepecha)',    color: '#43c529' },
      { label: 'Tlaxcalan',              value: 'Tlaxcalan',              color: '#2991c5' },
      { label: 'Zapotec',                value: 'Zapotec',                color: '#ab29c5' },
    ],
    dataUrl: './data/postclassical-empires.geojson',
    visible: false,
    description: 'Aztec, Tlaxcalan, Zapotec and others (~900–1521 CE)',
    sourceUrl: null,
  },
  {
    id: 'maya-culture-areas',
    group: 'Empires & Culture',
        label: 'Maya Culture Areas',
    color: '#2e7d32',
    mapboxType: 'fill',
    featureColor: true,
    colorBy: 'name',
    colorLegend: [
      { label: 'Central Mexico',               value: 'Central Mexico',               color: '#bd6032' },
      { label: 'Guerrero',                     value: 'Guerrero',                     color: '#bdbd32' },
      { label: 'Huasteca',                     value: 'Huasteca',                     color: '#60bd32' },
      { label: 'Maya Highlands',               value: 'Maya Highlands',               color: '#32bd60' },
      { label: 'Maya Lowlands',                value: 'Maya Lowlands',                color: '#32bdbd' },
      { label: 'Oaxaca',                       value: 'Oaxaca',                       color: '#3260bd' },
      { label: 'Southern Periphery',           value: 'Southern Periphery',           color: '#6032bd' },
      { label: 'Veracruz-Tabasco',             value: 'Veracruz-Tabasco',             color: '#bd32bd' },
      { label: 'Western and Northern Frontier', value: 'Western and Northern Frontier', color: '#bd3260' },
    ],
    dataUrl: './data/maya-culture-areas.geojson',
    visible: false,
    description: '39 Maya sub-regional culture zones',
    sourceUrl: null,
  },
  {
    id: 'mayan-sites',
    group: 'Empires & Culture',
        label: 'Maya Sites (ArcGIS)',
    color: '#00838f',
    mapboxType: 'circle',
    dataUrl: './data/mayan-sites.geojson',
    visible: false,
    description: '55 Maya sites (GIS for Humanities, San Antonio University)',
    sourceUrl: null,
  },
  {
    id: 'aztec-villages',
    group: 'Empires & Culture',
        label: 'Aztec Villages',
    color: '#e65100',
    mapboxType: 'circle',
    dataUrl: './data/aztec-villages.geojson',
    visible: false,
    description: '35 Aztec villages near Tenochtitlan (GIS for Humanities)',
    sourceUrl: null,
  },

  // ── Languages ────────────────────────────────────────────────────────────
  {
    id: 'language-families',
    group: 'Languages',
        label: 'Language Families',
    color: '#4527a0',
    mapboxType: 'fill',
    featureColor: true,
    colorBy: 'name',
    colorLegend: [
      { label: 'Chibchan',        value: 'Chibchan',        color: '#c6612e' },
      { label: 'Chocoan',         value: 'Chocoan',         color: '#c6842e' },
      { label: 'Chumashan',       value: 'Chumashan',       color: '#c6a72e' },
      { label: 'Coahuilteco',     value: 'Coahuilteco',     color: '#c2c62e' },
      { label: 'Cochimi-Yuman',   value: 'Cochimi-Yuman',   color: '#9fc62e' },
      { label: 'Comecrudan',      value: 'Comecrudan',      color: '#7cc62e' },
      { label: 'Cotoname',        value: 'Cotoname',        color: '#59c62e' },
      { label: 'Cuitlatec',       value: 'Cuitlatec',       color: '#36c62e' },
      { label: 'Guaicurian',      value: 'Guaicurian',      color: '#2ec649' },
      { label: 'Huavean',         value: 'Huavean',         color: '#2ec66c' },
      { label: 'Jicaquean',       value: 'Jicaquean',       color: '#2ec68f' },
      { label: 'Keresan',         value: 'Keresan',         color: '#2ec6b2' },
      { label: 'Kiowa-Tanoan',    value: 'Kiowa-Tanoan',    color: '#2eb6c6' },
      { label: 'Lencan',          value: 'Lencan',          color: '#2e93c6' },
      { label: 'Maratino',        value: 'Maratino',        color: '#2e70c6' },
      { label: 'Mayan',           value: 'Mayan',           color: '#2e4dc6' },
      { label: 'Misumalpan',      value: 'Misumalpan',      color: '#322ec6' },
      { label: 'Mixe-Zoque',      value: 'Mixe-Zoque',      color: '#552ec6' },
      { label: 'Otomanguean',     value: 'Otomanguean',     color: '#782ec6' },
      { label: 'Seri',            value: 'Seri',            color: '#9b2ec6' },
      { label: 'Tequistlatecan',  value: 'Tequistlatecan',  color: '#be2ec6' },
      { label: 'Totonacan',       value: 'Totonacan',       color: '#c62eab' },
      { label: 'Unclassifiable',  value: 'Unclassifiable',  color: '#c62e88' },
      { label: 'Uto-Aztecan',     value: 'Uto-Aztecan',     color: '#c62e64' },
      { label: 'Xincan',          value: 'Xincan',          color: '#c62e41' },
      { label: 'Zuni',            value: 'Zuni',            color: '#c63e2e' },
    ],
    dataUrl: './data/language-families.geojson',
    visible: false,
    description: '26 families — Asher & Moseley 2007, Atlas of the World\'s Languages (CC BY 4.0)',
    sourceUrl: 'https://github.com/glottography/asher2007world',
  },
  {
    id: 'language-dialects',
    group: 'Languages',
        label: 'Language Dialects (Meso-America)',
    color: '#4527a0',
    mapboxType: 'fill',
    featureColor: true,
    // colorBy 'name' uses the original GeoJSON property — no Python-added field required.
    // colorDetails drives the per-feature match expression; colorLegend drives the panel legend.
    colorBy: 'name',
    colorDetails: {
      '?Kaskan': '#23478e',
      '?Tekockin': '#2851a3',
      'Amusgo': '#6b8e23',
      'Amusgo, Amuzgo': '#7aa328',
      'Awakateko, Aguacatec, Aguateco': '#233e8e',
      'Central Nawa, Central Nahuatl': '#8e4323',
      'Central Sapoteko, Central Zapoteco': '#238e2c',
      'Chatino': '#89b72d',
      'Chiapaneko, Chiapaneco': '#8e236b',
      'Chinanteko, Chinanteco': '#b530c1',
      'Chocho Proper': '#238e79',
      'Chol': '#244092',
      'Choltí': '#254296',
      'Chontal (Of Oxaca)': '#2d5bb7',
      'Chorotega': '#d65bad',
      'Chortí': '#26439b',
      'Chuj': '#27459f',
      'Chumbia': '#279f87',
      'Eastern Nawa, Eastern Nahuatl': '#9f4b27',
      'Eastern Popoloka, Eastern Popoloca': '#2cb096',
      'Eastern Sapoteko, Eastern Zapoteco': '#28a333',
      'Eastern Soke, Zoque': '#59238e',
      'Eastern Tol': '#23748e',
      'Highland Sokean': '#62279d',
      'Isthmus Sokean': '#6b2aab',
      'Itzá': '#2847a3',
      'Ixil': '#2949a7',
      'Ixtenco Otomí': '#8e6e23',
      'Jalisco Otomí': '#987526',
      'Kabil, Cabil': '#8e3923',
      'Kakaopera, Cacaopera, Misumalpan': '#8e6223',
      'Kaqchikel': '#2a4aab',
      'Kare Lenka, Kare Lenca': '#a8432a',
      'Kiché, Quiché': '#2b4caf',
      'Koka': '#3366cc',
      'Kolo Lenka, Kolo Lenca': '#c14d30',
      'Kora, Cora': '#8e8023',
      'Kotoke, Cotoque': '#d6a35b',
      'Kwikateko, Cuicateco': '#30c1a4',
      'Kwitlateko, Cuitlateco': '#4775d1',
      'Lenka Proper, Lenca Proper': '#cf5e42',
      'Mam': '#2c4eb3',
      'Masateko, Mazateco': '#39cdb0',
      'Masawa, Mazahua': '#a17d28',
      'Matlatzinkan, Matlatzinca, Ocuilteco': '#aa842a',
      'Mije, Mixe': '#742eba',
      'Mopán': '#2d50b7',
      'Nawa': '#b0532c',
      'No label': '#5b84d6',
      'Northeastern Otomí': '#b38b2c',
      'Northern Misteko, Northern Mixteco': '#99cc33',
      'Northern Nawa, Northern Nahuatl': '#c15c30',
      'Northern Popoloka, Northern Popoloca': '#4ad1b6',
      'Northern Sapoteko, Northern Zapoteco': '#2db739',
      'Northwestern Otomí': '#bd922f',
      'Oluta Mijean, Oluteko, Oluta Popoluc': '#7d32c9',
      'Otomí': '#c69931',
      'Pame, Pamean': '#cc9f36',
      'Pinome': '#cfa43f',
      'Pipil': '#cd6639',
      'Pochuteko': '#d1734a',
      'Poqomam, Pokomam': '#2e52bb',
      'Poqomchí, Pokomchí': '#2f53bf',
      'Qanjobal, Kanjobal': '#3055c3',
      'Qeqchí, Kekchí': '#3157c7',
      'Sakapulteko': '#3359cc',
      'Sapoteko, Zapoteco': '#33cc3f',
      'Sayula Mijean, Sayulteko, Sayula Popoluca': '#863ece',
      'Serkin Lenka, Serkin Lenca': '#d6745b',
      'Shinkan, Xinca': '#3030c1',
      'Sipakapenyo, Sipacapense': '#375ccd',
      'Southern Misteko, Southern Mixteco': '#a3d147',
      'Southern Sapoteko, Southern Zapoteco': '#47d152',
      'Sutiaba': '#23858e',
      'Tapachula Mijean, Tapachulteko, Mixe': '#8f4dd2',
      'Teko, Teco': '#3b5fce',
      'Tekwexe': '#d1a849',
      'Tepewa, Tepehua': '#8e233e',
      'Tilapa Otomí': '#d3ad52',
      'Tlapaneko, Tlapaneco': '#5bcbd6',
      'Tojolabal': '#3f63cf',
      'Tolimeko, Tolimeco': '#309dc1',
      'Totonako, Totonaco': '#d65b7a',
      'Triki, Trique': '#add65b',
      'Tzeltal': '#4366d0',
      'Tzotzil': '#4769d1',
      'Tzuljil': '#4b6dd2',
      'Uspanteko, Uspanteco': '#4f70d3',
      'Wasteko, Huasteco': '#5373d4',
      'Wavi, Huave': '#30c185',
      'Western Nawa, Western Nahuatl': '#d6805b',
      'Western Otomí': '#d6b15b',
      'Western Popoloka, Western Popoloca': '#5bd6bd',
      'Western Sapoteko, Western Zapoteco': '#5bd666',
      'Western Soke, Zoque': '#995bd6',
      'Western Tol': '#5bb7d6',
      'Wichol, Huichol': '#d6c55b',
      'Yokotán, Chontal Maya': '#5777d5',
      'Yukateko, Yucatec Proper , Yucateco Proper': '#5b7ad6',
    },
    colorLegend: [
      { label: 'Mayan',        value: 'Mayan',        color: '#3055c3', count: 26 },
      { label: 'Nahuan',       value: 'Nahuan',       color: '#c35d30', count: 7  },
      { label: 'Otomian',      value: 'Otomian',      color: '#c39730', count: 12 },
      { label: 'Zapotecan',    value: 'Zapotecan',    color: '#30c33d', count: 6  },
      { label: 'Mixtecan',     value: 'Mixtecan',     color: '#92c330', count: 6  },
      { label: 'Mixe-Zoquean', value: 'Mixe-Zoquean', color: '#7a30c3', count: 8  },
      { label: 'Popolocan',    value: 'Popolocan',    color: '#30c3a6', count: 7  },
      { label: 'Lencan',       value: 'Lencan',       color: '#c34e30', count: 5  },
      { label: 'Totonacan',    value: 'Totonacan',    color: '#c33055', count: 2  },
      { label: 'Chinantec',    value: 'Chinantec',    color: '#b730c3', count: 1  },
      { label: 'Tlapanec',     value: 'Tlapanec',     color: '#30b7c3', count: 2  },
      { label: 'Chiapanec',    value: 'Chiapanec',    color: '#c33092', count: 2  },
      { label: 'Uto-Aztecan',  value: 'Uto-Aztecan',  color: '#c3b030', count: 2  },
      { label: 'Tol',          value: 'Tol',          color: '#309fc3', count: 3  },
      { label: 'Xincan',       value: 'Xincan',       color: '#3030c3', count: 1  },
      { label: 'Huave',        value: 'Huave',        color: '#30c386', count: 1  },
      { label: 'Misumalpan',   value: 'Misumalpan',   color: '#c38630', count: 2  },
      { label: 'Other',        value: 'Other',        color: '#3061c3', count: 6  },
    ],
    dataUrl: './data/language-dialects.geojson',
    visible: false,
    description: '99 dialect/language polygons from Map 10 — Asher & Moseley 2007, Atlas of the World\'s Languages (CC BY 4.0)',
    sourceUrl: 'https://github.com/glottography/asher2007world',
  },

  // ── LIDAR & Settlement ───────────────────────────────────────────────────
  {
    id: 'lidar-coverage',
    group: 'LiDAR & Settlement',
        label: 'LIDAR Survey Coverage (2019)',
    color: '#00bcd4',
    mapboxType: 'fill',
    dataUrl: './data/lidar-coverage.geojson',
    visible: false,
    description: '99 LIDAR survey footprints across the Maya area, 2009–2019 (MarigisLab / MARI at Tulane University)',
    sourceUrl: 'https://marigis.tulane.edu/',
  },
  {
    id: 'lidar-coverage-2022',
    group: 'LiDAR & Settlement',
        label: 'LIDAR Survey Coverage (2022)',
    color: '#0097a7',
    mapboxType: 'fill',
    dataUrl: './data/lidar-coverage-2022.geojson',
    visible: false,
    description: '105 LIDAR survey footprints across the Maya area through 2022 — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },
  {
    id: 'maya-settlement-groups',
    group: 'LiDAR & Settlement',
        label: 'Maya Settlement Groups (LIDAR)',
    color: '#ff7043',
    mapboxType: 'fill',
    featureColor: true,
    colorBy: 'site',
    colorLegend: [
      { label: 'Chactun',         value: 'Chactun',         color: '#ca632f' },
      { label: 'EREDD',           value: 'EREDD',           color: '#96ca2f' },
      { label: 'GLiHT-SouthCamp', value: 'GLiHT-SouthCamp', color: '#2fca63' },
      { label: 'Holmul',          value: 'Holmul',          color: '#2f96ca' },
      { label: 'La Corona',       value: 'La Corona',       color: '#632fca' },
      { label: 'Tikal',           value: 'Tikal',           color: '#ca2f96' },
    ],
    dataUrl: './data/maya-settlement-groups.geojson',
    visible: false,
    description: '1,499 large & medium settlement group polygons from Tikal, Holmul, La Corona, Chactun, G-LiHT & EREDD LIDAR surveys — Estrada-Belli et al., PACUNAM / NASA G-LiHT (MarigisLab / MARI at Tulane University)',
    sourceUrl: 'https://marigis.tulane.edu/',
  },
  {
    id: 'pacunam-survey-units',
    group: 'LiDAR & Settlement',
        label: 'PACUNAM LiDAR Survey Units',
    color: '#26c6da',
    mapboxType: 'fill',
    dataUrl: './data/pacunam-survey-units.geojson',
    visible: false,
    description: '12 PACUNAM LiDAR Initiative survey unit polygons — Estrada-Belli et al. (MarigisLab / MARI at Tulane University)',
    sourceUrl: 'https://marigis.tulane.edu/',
  },
  {
    id: 'la-milpa',
    group: 'LiDAR & Settlement',
        label: 'La Milpa Settlement, Belize',
    color: '#ab47bc',
    mapboxType: 'fill',
    dataUrl: './data/la-milpa.geojson',
    visible: false,
    description: '~10,000 structures, berms & survey boundaries across 4 field campaigns (LMBU, Scarborough, Kunen, Robichaux) — Boston University / Tulane University La Milpa project (MarigisLab / MARI at Tulane University)',
    sourceUrl: 'https://marigis.tulane.edu/',
  },
  {
    id: 'pulltrouser-swamp',
    group: 'LiDAR & Settlement',
        label: 'Pulltrouser Swamp Settlement (Belize)',
    color: '#43a047',
    mapboxType: 'fill',
    dataUrl: './data/pulltrouser-swamp.geojson',
    visible: false,
    description: '525 structure polygons + 13 survey areas, Pulltrouser Swamp, Belize — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },
  {
    id: 'pulltrouser-swamp-points',
    group: 'LiDAR & Settlement',
        label: 'Pulltrouser Swamp Structures (points)',
    color: '#66bb6a',
    mapboxType: 'circle',
    dataUrl: './data/pulltrouser-swamp-points.geojson',
    visible: false,
    description: '399 structure & platform points, Pulltrouser Swamp, Belize — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },
  {
    id: 'becan',
    group: 'LiDAR & Settlement',
        label: 'Becan Settlement, Campeche (polygons)',
    color: '#f57f17',
    mapboxType: 'fill',
    dataUrl: './data/becan.geojson',
    visible: false,
    description: '2,295 structure polygons + survey area & blocks, Becan, Campeche, Mexico — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },
  {
    id: 'becan-points',
    group: 'LiDAR & Settlement',
        label: 'Becan Structures, Campeche (points)',
    color: '#ffb300',
    mapboxType: 'circle',
    dataUrl: './data/becan-points.geojson',
    visible: false,
    description: '1,270 structure & platform points, Becan, Campeche, Mexico — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },

  // ── Physical Geography ───────────────────────────────────────────────────
  {
    id: 'volcanoes',
    group: 'Physical Geography',
        label: 'Holocene Volcanoes',
    color: '#d32f2f',
    mapboxType: 'circle',
    dataUrl: './data/volcanoes.geojson',
    visible: false,
    description: '87 Holocene volcanoes — Smithsonian Global Volcanism Program (public domain)',
    sourceUrl: 'https://volcano.si.edu/volcanolist_countries.cfm',
  },
  {
    id: 'faults-central-america',
    group: 'Physical Geography',
        label: 'Active Faults — Central America',
    color: '#b71c1c',
    mapboxType: 'line',
    lineWidth: 1.5,
    dataUrl: './data/faults-central-america.geojson',
    visible: false,
    description: '180 fault traces with slip rates and kinematics — CCAF-DB, GEM Foundation (CC-BY 4.0)',
    sourceUrl: 'https://github.com/GEMScienceTools/gem-global-active-faults',
  },
  {
    id: 'faults-mexico',
    group: 'Physical Geography',
        label: 'Active Faults — Mexico',
    color: '#c62828',
    mapboxType: 'line',
    lineWidth: 1.5,
    dataUrl: './data/faults-mexico.geojson',
    visible: false,
    description: '715 fault traces — GEM Global Active Faults, Mexico portion (CC-BY-SA 4.0)',
    sourceUrl: 'https://github.com/GEMScienceTools/gem-global-active-faults',
  },
  {
    id: 'earthquakes',
    group: 'Physical Geography',
        label: 'Earthquakes (M5.0+, 1900–2024)',
    color: '#ff6f00',
    mapboxType: 'circle',
    dataUrl: './data/earthquakes.geojson',
    visible: false,
    description: '2,000 largest M5.0+ earthquakes — USGS Earthquake Catalog (public domain)',
    sourceUrl: 'https://earthquake.usgs.gov/earthquakes/search/',
  },
  {
    id: 'major-rivers',
    group: 'Physical Geography',
        label: 'Major Rivers',
    color: '#0288d1',
    mapboxType: 'line',
    lineWidth: 1.5,
    dataUrl: './data/major-rivers.geojson',
    visible: false,
    description: '21,531 river segments (Strahler order ≥5) — HydroRIVERS v10, WWF / USGS HydroSHEDS (CC-BY 4.0)',
    sourceUrl: 'https://www.hydrosheds.org/products/hydrorivers',
  },
  {
    id: 'major-lakes',
    group: 'Physical Geography',
        label: 'Major Lakes',
    color: '#0277bd',
    mapboxType: 'fill',
    dataUrl: './data/major-lakes.geojson',
    visible: false,
    description: '23 major lakes — Natural Earth 10m Physical (public domain)',
    sourceUrl: 'https://www.naturalearthdata.com/downloads/10m-physical-vectors/',
  },
  {
    id: 'hurricane-tracks',
    group: 'Physical Geography',
        label: 'Hurricane Tracks (1851–2023)',
    color: '#6a1b9a',
    mapboxType: 'line',
    lineWidth: 1,
    dataUrl: './data/hurricane-tracks.geojson',
    visible: false,
    description: '1,614 Atlantic basin storm tracks intersecting Mesoamerica — NOAA IBTrACS v04r01 (public domain)',
    sourceUrl: 'https://www.ncei.noaa.gov/products/international-best-track-archive',
  },
  {
    id: 'coral-reefs',
    group: 'Physical Geography',
        label: 'Coral Reefs',
    color: '#ff6e40',
    mapboxType: 'fill',
    dataUrl: './data/coral-reefs.geojson',
    visible: false,
    description: '328 reef polygons in the Caribbean — OpenStreetMap (ODbL)',
    sourceUrl: 'https://www.openstreetmap.org/',
  },
  {
    id: 'ramsar-wetlands',
    group: 'Physical Geography',
        label: 'Ramsar Wetlands',
    color: '#00796b',
    mapboxType: 'circle',
    dataUrl: './data/ramsar-wetlands.geojson',
    visible: false,
    description: '23 Ramsar-designated wetlands of international importance — OpenStreetMap / Ramsar Convention (ODbL)',
    sourceUrl: 'https://rsis.ramsar.org/',
  },

  // ── Ecology & Environment ────────────────────────────────────────────────
  {
    id: 'ecoregions',
    group: 'Ecology & Environment',
        label: 'Terrestrial Ecoregions',
    color: '#558b2f',
    mapboxType: 'fill',
    featureColor: true,
    colorBy: 'biome',
    colorLegend: [
      { label: 'Dry Forest',        value: 'Dry Forest',        color: '#bd9537', count: 15 },
      { label: 'Montane Forest',    value: 'Montane Forest',    color: '#37bda7', count: 14 },
      { label: 'Moist Forest',      value: 'Moist Forest',      color: '#37bd37', count: 13 },
      { label: 'Other',             value: 'Other',             color: '#9037bd', count: 12 },
      { label: 'Grassland/Savanna', value: 'Grassland/Savanna', color: '#bdb237', count: 7  },
      { label: 'Mangroves',         value: 'Mangroves',         color: '#37bd7a', count: 6  },
      { label: 'Wetlands',          value: 'Wetlands',          color: '#379cbd', count: 2  },
    ],
    dataUrl: './data/ecoregions.geojson',
    visible: false,
    description: '69 ecoregions — RESOLVE Ecoregions 2017, WWF / Dinerstein et al. (CC-BY 4.0)',
    sourceUrl: 'https://ecoregions.appspot.com/',
  },
  {
    id: 'mangroves-2020',
    group: 'Ecology & Environment',
        label: 'Mangrove Coverage (2020)',
    color: '#1b5e20',
    mapboxType: 'fill',
    dataUrl: './data/mangroves-2020.geojson',
    visible: false,
    description: '147 mangrove tile polygons — Global Mangrove Watch 2020, JAXA / Aberystwyth (CC-BY 4.0)',
    sourceUrl: 'https://www.globalmangrovewatch.org/',
  },
  {
    id: 'protected-areas',
    group: 'Ecology & Environment',
        label: 'Protected Areas (WDPA)',
    color: '#33691e',
    mapboxType: 'fill',
    dataUrl: './data/protected-areas.geojson',
    visible: false,
    description: '2,043 protected areas — World Database on Protected Areas, UNEP-WCMC / IUCN',
    sourceUrl: 'https://www.protectedplanet.net/en',
  },
  {
    id: 'culturally-significant-species',
    group: 'Ecology & Environment',
        label: 'Culturally Significant Species',
    color: '#00c853',
    mapboxType: 'circle',
    featureColor: true,
    colorBy: 'subtype',
    colorLegend: [
      { label: 'Panthera (Jaguar)',    value: 'Panthera',    color: '#d97706' },
      { label: 'Pharomachrus (Quetzal)', value: 'Pharomachrus', color: '#059669' },
    ],
    dataUrl: './data/culturally-significant-species.geojson',
    visible: false,
    description: '600 occurrences: Resplendent Quetzal, Jaguar — GBIF / iNaturalist (CC-BY)',
    sourceUrl: 'https://www.gbif.org/',
  },

  // ── Conflict & Security ──────────────────────────────────────────────────
  {
    id: 'migration-flows',
    group: 'Conflict & History',
    label: 'Migration & Displacement Corridors',
    color: '#7a82a8',
    mapboxType: 'line',
    dataUrl: './data/migration-flows.geojson',
    visible: false,
    description: 'Major migration and displacement corridors — Guatemala & El Salvador, 1954–present. Colored by era; dashed lines indicate deportation flows.',
    sourceUrl: null,
    colorBy: 'era',
    colorLegend: [
      { label: 'Cold War Origins (1950–1979)',       value: 1, color: '#6366f1' },
      { label: 'Peak Civil War (1979–1992)',          value: 2, color: '#dc2626' },
      { label: 'Post-War & Gang Seeding (1992–2000)', value: 3, color: '#d97706' },
      { label: 'Gang Violence Era (2000–2014)',       value: 4, color: '#ea580c' },
      { label: 'Caravan Era (2014–2021)',             value: 5, color: '#7c3aed' },
      { label: 'Divergence (2022–present)',           value: 6, color: '#0891b2' },
    ],
  },
  {
    id: 'modern-conflict-sites',
    group: 'Conflict & History',
        label: 'Modern Conflict Sites',
    color: '#b71c1c',
    mapboxType: 'circle',
    dataUrl: './data/modern-conflict-sites.geojson',
    visible: false,
    description: 'Massacre sites, military bases, and conflict zones — 20th-century US intervention in Central America (The Long Shadow)',
    sourceUrl: null,
  },
  {
    id: 'conflict-events',
    group: 'Conflict & History',
        label: 'Conflict Events (2022–2023)',
    color: '#c62828',
    mapboxType: 'circle',
    featureColor: true,
    colorBy: 'event_subtype',
    colorLegend: [
      { label: 'Battles',                    value: 'Battles',                        color: '#dc2626' },
      { label: 'Explosions/Remote violence', value: 'Explosions/Remote violence',     color: '#d97706' },
      { label: 'Violence against civilians', value: 'Violence against civilians',     color: '#7c2d12' },
      { label: 'Riots',                      value: 'Riots',                          color: '#9333ea' },
      { label: 'Protests',                   value: 'Protests',                       color: '#2563eb' },
      { label: 'Strategic developments',     value: 'Strategic developments',         color: '#059669' },
    ],
    dataUrl: './data/conflict-events.geojson',
    visible: false,
    description: '10,781 georeferenced conflict/violence events — HDX / ACLED-sourced (CC BY-NC-SA)',
    sourceUrl: 'https://data.humdata.org/',
  },

  // ── Modern Administrative ────────────────────────────────────────────────
  {
    id: 'admin2-boundaries',
    group: 'Modern Administrative',
        label: 'Municipalities / Districts (ADM-2)',
    color: '#455a64',
    mapboxType: 'fill',
    dataUrl: './data/admin2-boundaries.geojson',
    visible: false,
    description: '3,636 municipalities & districts across 7 countries — geoBoundaries v6.0 (CC-BY 4.0)',
    sourceUrl: 'https://www.geoboundaries.org/',
  },
  {
    id: 'urban-areas',
    group: 'Modern Administrative',
        label: 'Urban Areas',
    color: '#78909c',
    mapboxType: 'fill',
    dataUrl: './data/urban-areas.geojson',
    visible: false,
    description: '289 urban footprint polygons — Natural Earth 10m Cultural (public domain)',
    sourceUrl: 'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/',
  },
  {
    id: 'major-roads',
    group: 'Modern Administrative',
        label: 'Major Roads',
    color: '#546e7a',
    mapboxType: 'line',
    lineWidth: 1,
    dataUrl: './data/major-roads.geojson',
    visible: false,
    description: '329 major road segments — Natural Earth 10m Cultural (public domain)',
    sourceUrl: 'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/',
  },

  // ── Disabled / Pending ───────────────────────────────────────────────────
  {
    id: 'artifacts',
    group: 'Modern Administrative',
        label: 'Artifacts',
    color: '#1565c0',
    mapboxType: 'circle',
    dataUrl: null,
    visible: false,
    description: 'Excavated artifacts by location (add via form)',
    sourceUrl: null,
    disabled: true,
  },
]
