export const LAYER_REGISTRY = [
  // ── Archaeology & Sites ──────────────────────────────────────────────────
  {
    id: 'sites',
    label: 'Archaeological Sites',
    color: '#e85d04',
    mapboxType: 'circle',
    dataUrl: './data/sites.geojson',
    visible: true,
    description: 'Known sites sourced from Pleiades and Wikidata',
    sourceUrl: 'https://pleiades.stoa.org/',
  },
  {
    id: 'maya-inscriptions',
    label: 'Maya Inscription Sites',
    color: '#0077b6',
    mapboxType: 'circle',
    dataUrl: './data/maya-inscriptions.geojson',
    visible: false,
    description: '314 sites with recorded Maya inscriptions (Kaggle / ujwalkandi)',
    sourceUrl: 'https://www.kaggle.com/datasets/ujwalkandi/maya-inscriptions',
  },
  {
    id: 'inah-archaeological-zones',
    label: 'INAH Archaeological Zones (Mexico)',
    color: '#b5451b',
    mapboxType: 'circle',
    dataUrl: './data/inah-archaeological-zones.geojson',
    visible: false,
    description: '494 officially open pre-Hispanic zones in Mexico (INAH / Wikidata)',
    sourceUrl: 'https://www.wikidata.org/',
  },
  {
    id: 'unesco-world-heritage',
    label: 'UNESCO World Heritage Sites',
    color: '#1565c0',
    mapboxType: 'circle',
    dataUrl: './data/unesco-world-heritage.geojson',
    visible: false,
    description: '50 WHC sites in Mesoamerica — UNESCO DataHub (open access)',
    sourceUrl: 'https://whc.unesco.org/en/list/',
  },
  {
    id: 'lidar-surveys-opentopography',
    label: 'Open LiDAR Surveys (OpenTopography)',
    color: '#7b1fa2',
    mapboxType: 'circle',
    dataUrl: './data/lidar-surveys-opentopography.geojson',
    visible: false,
    description: '4 publicly archived archaeological LiDAR surveys — OpenTopography / NSF (CC-BY)',
    sourceUrl: 'https://opentopography.org/catalog',
  },

  // ── Empires & Culture ────────────────────────────────────────────────────
  {
    id: 'classical-empires',
    label: 'Classical Empires',
    color: '#7b2d8b',
    mapboxType: 'fill',
    dataUrl: './data/classical-empires.geojson',
    visible: false,
    description: 'Teotihuacan, Zapotec, Maya and others (~100 BCE–900 CE)',
    sourceUrl: null,
  },
  {
    id: 'postclassical-empires',
    label: 'Post-Classical Empires',
    color: '#c2185b',
    mapboxType: 'fill',
    dataUrl: './data/postclassical-empires.geojson',
    visible: false,
    description: 'Aztec, Tlaxcalan, Zapotec and others (~900–1521 CE)',
    sourceUrl: null,
  },
  {
    id: 'maya-culture-areas',
    label: 'Maya Culture Areas',
    color: '#2e7d32',
    mapboxType: 'fill',
    dataUrl: './data/maya-culture-areas.geojson',
    visible: false,
    description: '39 Maya sub-regional culture zones',
    sourceUrl: null,
  },
  {
    id: 'mayan-sites',
    label: 'Maya Sites (ArcGIS)',
    color: '#00838f',
    mapboxType: 'circle',
    dataUrl: './data/mayan-sites.geojson',
    visible: false,
    description: '55 Maya sites (GIS for Humanities, San Antonio University)',
    sourceUrl: null,
  },
  {
    id: 'aztec-villages',
    label: 'Aztec Villages',
    color: '#e65100',
    mapboxType: 'circle',
    dataUrl: './data/aztec-villages.geojson',
    visible: false,
    description: '35 Aztec villages near Tenochtitlan (GIS for Humanities)',
    sourceUrl: null,
  },

  // ── Languages ────────────────────────────────────────────────────────────
  {
    id: 'language-families',
    label: 'Language Families',
    color: '#4527a0',
    mapboxType: 'fill',
    featureColor: true,
    dataUrl: './data/language-families.geojson',
    visible: false,
    description: '26 families — Asher & Moseley 2007, Atlas of the World\'s Languages (CC BY 4.0)',
    sourceUrl: 'https://github.com/glottography/asher2007world',
  },
  {
    id: 'language-dialects',
    label: 'Language Dialects (Meso-America)',
    color: '#4527a0',
    mapboxType: 'fill',
    featureColor: true,
    dataUrl: './data/language-dialects.geojson',
    visible: false,
    description: '99 dialect/language polygons from Map 10 — Asher & Moseley 2007, Atlas of the World\'s Languages (CC BY 4.0)',
    sourceUrl: 'https://github.com/glottography/asher2007world',
  },

  // ── LIDAR & Settlement ───────────────────────────────────────────────────
  {
    id: 'lidar-coverage',
    label: 'LIDAR Survey Coverage (2019)',
    color: '#00bcd4',
    mapboxType: 'fill',
    dataUrl: './data/lidar-coverage.geojson',
    visible: false,
    description: '99 LIDAR survey footprints across the Maya area, 2009–2019 (MarigisLab / MARI at Tulane University)',
    sourceUrl: 'https://marigis.tulane.edu/',
  },
  {
    id: 'lidar-coverage-2022',
    label: 'LIDAR Survey Coverage (2022)',
    color: '#0097a7',
    mapboxType: 'fill',
    dataUrl: './data/lidar-coverage-2022.geojson',
    visible: false,
    description: '105 LIDAR survey footprints across the Maya area through 2022 — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },
  {
    id: 'maya-settlement-groups',
    label: 'Maya Settlement Groups (LIDAR)',
    color: '#ff7043',
    mapboxType: 'fill',
    dataUrl: './data/maya-settlement-groups.geojson',
    visible: false,
    description: '1,499 large & medium settlement group polygons from Tikal, Holmul, La Corona, Chactun, G-LiHT & EREDD LIDAR surveys — Estrada-Belli et al., PACUNAM / NASA G-LiHT (MarigisLab / MARI at Tulane University)',
    sourceUrl: 'https://marigis.tulane.edu/',
  },
  {
    id: 'pacunam-survey-units',
    label: 'PACUNAM LiDAR Survey Units',
    color: '#26c6da',
    mapboxType: 'fill',
    dataUrl: './data/pacunam-survey-units.geojson',
    visible: false,
    description: '12 PACUNAM LiDAR Initiative survey unit polygons — Estrada-Belli et al. (MarigisLab / MARI at Tulane University)',
    sourceUrl: 'https://marigis.tulane.edu/',
  },
  {
    id: 'la-milpa',
    label: 'La Milpa Settlement, Belize',
    color: '#ab47bc',
    mapboxType: 'fill',
    dataUrl: './data/la-milpa.geojson',
    visible: false,
    description: '~10,000 structures, berms & survey boundaries across 4 field campaigns (LMBU, Scarborough, Kunen, Robichaux) — Boston University / Tulane University La Milpa project (MarigisLab / MARI at Tulane University)',
    sourceUrl: 'https://marigis.tulane.edu/',
  },
  {
    id: 'pulltrouser-swamp',
    label: 'Pulltrouser Swamp Settlement (Belize)',
    color: '#43a047',
    mapboxType: 'fill',
    dataUrl: './data/pulltrouser-swamp.geojson',
    visible: false,
    description: '525 structure polygons + 13 survey areas, Pulltrouser Swamp, Belize — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },
  {
    id: 'pulltrouser-swamp-points',
    label: 'Pulltrouser Swamp Structures (points)',
    color: '#66bb6a',
    mapboxType: 'circle',
    dataUrl: './data/pulltrouser-swamp-points.geojson',
    visible: false,
    description: '399 structure & platform points, Pulltrouser Swamp, Belize — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },
  {
    id: 'becan',
    label: 'Becan Settlement, Campeche (polygons)',
    color: '#f57f17',
    mapboxType: 'fill',
    dataUrl: './data/becan.geojson',
    visible: false,
    description: '2,295 structure polygons + survey area & blocks, Becan, Campeche, Mexico — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },
  {
    id: 'becan-points',
    label: 'Becan Structures, Campeche (points)',
    color: '#ffb300',
    mapboxType: 'circle',
    dataUrl: './data/becan-points.geojson',
    visible: false,
    description: '1,270 structure & platform points, Becan, Campeche, Mexico — ancientmayasettlement.com / MARI at Tulane University',
    sourceUrl: 'https://www.ancientmayasettlement.com/',
  },

  // ── Physical Geography ───────────────────────────────────────────────────
  {
    id: 'volcanoes',
    label: 'Holocene Volcanoes',
    color: '#d32f2f',
    mapboxType: 'circle',
    dataUrl: './data/volcanoes.geojson',
    visible: false,
    description: '87 Holocene volcanoes — Smithsonian Global Volcanism Program (public domain)',
    sourceUrl: 'https://volcano.si.edu/volcanolist_countries.cfm',
  },
  {
    id: 'faults-central-america',
    label: 'Active Faults — Central America',
    color: '#b71c1c',
    mapboxType: 'line',
    lineWidth: 1.5,
    dataUrl: './data/faults-central-america.geojson',
    visible: false,
    description: '180 fault traces with slip rates and kinematics — CCAF-DB, GEM Foundation (CC-BY 4.0)',
    sourceUrl: 'https://github.com/GEMScienceTools/gem-global-active-faults',
  },
  {
    id: 'faults-mexico',
    label: 'Active Faults — Mexico',
    color: '#c62828',
    mapboxType: 'line',
    lineWidth: 1.5,
    dataUrl: './data/faults-mexico.geojson',
    visible: false,
    description: '715 fault traces — GEM Global Active Faults, Mexico portion (CC-BY-SA 4.0)',
    sourceUrl: 'https://github.com/GEMScienceTools/gem-global-active-faults',
  },
  {
    id: 'earthquakes',
    label: 'Earthquakes (M5.0+, 1900–2024)',
    color: '#ff6f00',
    mapboxType: 'circle',
    dataUrl: './data/earthquakes.geojson',
    visible: false,
    description: '2,000 largest M5.0+ earthquakes — USGS Earthquake Catalog (public domain)',
    sourceUrl: 'https://earthquake.usgs.gov/earthquakes/search/',
  },
  {
    id: 'major-rivers',
    label: 'Major Rivers',
    color: '#0288d1',
    mapboxType: 'line',
    lineWidth: 1.5,
    dataUrl: './data/major-rivers.geojson',
    visible: false,
    description: '21,531 river segments (Strahler order ≥5) — HydroRIVERS v10, WWF / USGS HydroSHEDS (CC-BY 4.0)',
    sourceUrl: 'https://www.hydrosheds.org/products/hydrorivers',
  },
  {
    id: 'major-lakes',
    label: 'Major Lakes',
    color: '#0277bd',
    mapboxType: 'fill',
    dataUrl: './data/major-lakes.geojson',
    visible: false,
    description: '23 major lakes — Natural Earth 10m Physical (public domain)',
    sourceUrl: 'https://www.naturalearthdata.com/downloads/10m-physical-vectors/',
  },
  {
    id: 'hurricane-tracks',
    label: 'Hurricane Tracks (1851–2023)',
    color: '#6a1b9a',
    mapboxType: 'line',
    lineWidth: 1,
    dataUrl: './data/hurricane-tracks.geojson',
    visible: false,
    description: '1,614 Atlantic basin storm tracks intersecting Mesoamerica — NOAA IBTrACS v04r01 (public domain)',
    sourceUrl: 'https://www.ncei.noaa.gov/products/international-best-track-archive',
  },
  {
    id: 'coral-reefs',
    label: 'Coral Reefs',
    color: '#ff6e40',
    mapboxType: 'fill',
    dataUrl: './data/coral-reefs.geojson',
    visible: false,
    description: '328 reef polygons in the Caribbean — OpenStreetMap (ODbL)',
    sourceUrl: 'https://www.openstreetmap.org/',
  },
  {
    id: 'ramsar-wetlands',
    label: 'Ramsar Wetlands',
    color: '#00796b',
    mapboxType: 'circle',
    dataUrl: './data/ramsar-wetlands.geojson',
    visible: false,
    description: '23 Ramsar-designated wetlands of international importance — OpenStreetMap / Ramsar Convention (ODbL)',
    sourceUrl: 'https://rsis.ramsar.org/',
  },

  // ── Ecology & Environment ────────────────────────────────────────────────
  {
    id: 'ecoregions',
    label: 'Terrestrial Ecoregions',
    color: '#558b2f',
    mapboxType: 'fill',
    featureColor: true,
    dataUrl: './data/ecoregions.geojson',
    visible: false,
    description: '69 ecoregions — RESOLVE Ecoregions 2017, WWF / Dinerstein et al. (CC-BY 4.0)',
    sourceUrl: 'https://ecoregions.appspot.com/',
  },
  {
    id: 'mangroves-2020',
    label: 'Mangrove Coverage (2020)',
    color: '#1b5e20',
    mapboxType: 'fill',
    dataUrl: './data/mangroves-2020.geojson',
    visible: false,
    description: '147 mangrove tile polygons — Global Mangrove Watch 2020, JAXA / Aberystwyth (CC-BY 4.0)',
    sourceUrl: 'https://www.globalmangrovewatch.org/',
  },
  {
    id: 'protected-areas',
    label: 'Protected Areas (WDPA)',
    color: '#33691e',
    mapboxType: 'fill',
    dataUrl: './data/protected-areas.geojson',
    visible: false,
    description: '2,043 protected areas — World Database on Protected Areas, UNEP-WCMC / IUCN',
    sourceUrl: 'https://www.protectedplanet.net/en',
  },
  {
    id: 'culturally-significant-species',
    label: 'Culturally Significant Species',
    color: '#00c853',
    mapboxType: 'circle',
    featureColor: true,
    dataUrl: './data/culturally-significant-species.geojson',
    visible: false,
    description: '600 occurrences: Resplendent Quetzal, Jaguar — GBIF / iNaturalist (CC-BY)',
    sourceUrl: 'https://www.gbif.org/',
  },

  // ── Conflict & Security ──────────────────────────────────────────────────
  {
    id: 'modern-conflict-sites',
    label: 'Modern Conflict Sites',
    color: '#b71c1c',
    mapboxType: 'circle',
    dataUrl: './data/modern-conflict-sites.geojson',
    visible: false,
    description: 'Massacre sites, military bases, and conflict zones — 20th-century US intervention in Central America (The Long Shadow)',
    sourceUrl: null,
  },
  {
    id: 'conflict-events',
    label: 'Conflict Events (2022–2023)',
    color: '#c62828',
    mapboxType: 'circle',
    dataUrl: './data/conflict-events.geojson',
    visible: false,
    description: '10,781 georeferenced conflict/violence events — HDX / ACLED-sourced (CC BY-NC-SA)',
    sourceUrl: 'https://data.humdata.org/',
  },

  // ── Modern Administrative ────────────────────────────────────────────────
  {
    id: 'admin2-boundaries',
    label: 'Municipalities / Districts (ADM-2)',
    color: '#455a64',
    mapboxType: 'fill',
    dataUrl: './data/admin2-boundaries.geojson',
    visible: false,
    description: '3,636 municipalities & districts across 7 countries — geoBoundaries v6.0 (CC-BY 4.0)',
    sourceUrl: 'https://www.geoboundaries.org/',
  },
  {
    id: 'urban-areas',
    label: 'Urban Areas',
    color: '#78909c',
    mapboxType: 'fill',
    dataUrl: './data/urban-areas.geojson',
    visible: false,
    description: '289 urban footprint polygons — Natural Earth 10m Cultural (public domain)',
    sourceUrl: 'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/',
  },
  {
    id: 'major-roads',
    label: 'Major Roads',
    color: '#546e7a',
    mapboxType: 'line',
    lineWidth: 1,
    dataUrl: './data/major-roads.geojson',
    visible: false,
    description: '329 major road segments — Natural Earth 10m Cultural (public domain)',
    sourceUrl: 'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/',
  },

  // ── Disabled / Pending ───────────────────────────────────────────────────
  {
    id: 'artifacts',
    label: 'Artifacts',
    color: '#1565c0',
    mapboxType: 'circle',
    dataUrl: null,
    visible: false,
    description: 'Excavated artifacts by location (add via form)',
    sourceUrl: null,
    disabled: true,
  },
]
