-- ============================================================
-- Phase I seed: sources + layer_definitions
-- Generated from src/layers/index.js
-- Run in Supabase SQL Editor AFTER phase1_schema.sql
-- ============================================================

-- Sources
insert into public.sources (name, source_type, url, description) values
  ('Archaeological Sites', 'dataset', 'https://pleiades.stoa.org/', 'Known sites sourced from Pleiades and Wikidata'),
  ('Maya Inscription Sites', 'dataset', 'https://www.kaggle.com/datasets/ujwalkandi/maya-inscriptions', '314 sites with recorded Maya inscriptions (Kaggle / ujwalkandi)'),
  ('INAH Archaeological Zones (Mexico)', 'dataset', 'https://www.wikidata.org/', '494 officially open pre-Hispanic zones in Mexico (INAH / Wikidata)'),
  ('UNESCO World Heritage Sites', 'dataset', 'https://whc.unesco.org/en/list/', '50 WHC sites in Mesoamerica — UNESCO DataHub (open access)'),
  ('Open LiDAR Surveys (OpenTopography)', 'dataset', 'https://opentopography.org/catalog', '4 publicly archived archaeological LiDAR surveys — OpenTopography / NSF (CC-BY)'),
  ('Language Families', 'dataset', 'https://github.com/glottography/asher2007world', '26 families — Asher & Moseley 2007, Atlas of the World''s Languages (CC BY 4.0)'),
  ('LIDAR Survey Coverage (2019)', 'dataset', 'https://marigis.tulane.edu/', '99 LIDAR survey footprints across the Maya area, 2009–2019 (MarigisLab / MARI at Tulane University)'),
  ('LIDAR Survey Coverage (2022)', 'dataset', 'https://www.ancientmayasettlement.com/', '105 LIDAR survey footprints across the Maya area through 2022 — ancientmayasettlement.com / MARI at Tulane University'),
  ('Holocene Volcanoes', 'dataset', 'https://volcano.si.edu/volcanolist_countries.cfm', '87 Holocene volcanoes — Smithsonian Global Volcanism Program (public domain)'),
  ('Active Faults — Central America', 'dataset', 'https://github.com/GEMScienceTools/gem-global-active-faults', '180 fault traces with slip rates and kinematics — CCAF-DB, GEM Foundation (CC-BY 4.0)'),
  ('Earthquakes (M5.0+, 1900–2024)', 'dataset', 'https://earthquake.usgs.gov/earthquakes/search/', '2,000 largest M5.0+ earthquakes — USGS Earthquake Catalog (public domain)'),
  ('Major Rivers', 'dataset', 'https://www.hydrosheds.org/products/hydrorivers', '21,531 river segments (Strahler order ≥5) — HydroRIVERS v10, WWF / USGS HydroSHEDS (CC-BY 4.0)'),
  ('Major Lakes', 'dataset', 'https://www.naturalearthdata.com/downloads/10m-physical-vectors/', '23 major lakes — Natural Earth 10m Physical (public domain)'),
  ('Hurricane Tracks (1851–2023)', 'dataset', 'https://www.ncei.noaa.gov/products/international-best-track-archive', '1,614 Atlantic basin storm tracks intersecting Mesoamerica — NOAA IBTrACS v04r01 (public domain)'),
  ('Coral Reefs', 'dataset', 'https://www.openstreetmap.org/', '328 reef polygons in the Caribbean — OpenStreetMap (ODbL)'),
  ('Ramsar Wetlands', 'dataset', 'https://rsis.ramsar.org/', '23 Ramsar-designated wetlands of international importance — OpenStreetMap / Ramsar Convention (ODbL)'),
  ('Terrestrial Ecoregions', 'dataset', 'https://ecoregions.appspot.com/', '69 ecoregions — RESOLVE Ecoregions 2017, WWF / Dinerstein et al. (CC-BY 4.0)'),
  ('Mangrove Coverage (2020)', 'dataset', 'https://www.globalmangrovewatch.org/', '147 mangrove tile polygons — Global Mangrove Watch 2020, JAXA / Aberystwyth (CC-BY 4.0)'),
  ('Protected Areas (WDPA)', 'dataset', 'https://www.protectedplanet.net/en', '2,043 protected areas — World Database on Protected Areas, UNEP-WCMC / IUCN'),
  ('Culturally Significant Species', 'dataset', 'https://www.gbif.org/', '600 occurrences: Resplendent Quetzal, Jaguar — GBIF / iNaturalist (CC-BY)'),
  ('Conflict Events (2022–2023)', 'dataset', 'https://data.humdata.org/', '10,781 georeferenced conflict/violence events — HDX / ACLED-sourced (CC BY-NC-SA)'),
  ('Municipalities / Districts (ADM-2)', 'dataset', 'https://www.geoboundaries.org/', '3,636 municipalities & districts across 7 countries — geoBoundaries v6.0 (CC-BY 4.0)'),
  ('Urban Areas', 'dataset', 'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/', '289 urban footprint polygons — Natural Earth 10m Cultural (public domain)');

-- Layer definitions
insert into public.layer_definitions
  (id, label, description, entity_type, mapbox_type, color,
   visible_default, disabled, display_order, source_id)
values
  (
    'sites',
    'Archaeological Sites',
    'Known sites sourced from Pleiades and Wikidata',
    'place',
    'circle',
    '#e85d04',
    true,
    false,
    0,
    (select id from public.sources where url = 'https://pleiades.stoa.org/' limit 1)
  ),
  (
    'maya-inscriptions',
    'Maya Inscription Sites',
    '314 sites with recorded Maya inscriptions (Kaggle / ujwalkandi)',
    'place',
    'circle',
    '#0077b6',
    false,
    false,
    1,
    (select id from public.sources where url = 'https://www.kaggle.com/datasets/ujwalkandi/maya-inscriptions' limit 1)
  ),
  (
    'inah-archaeological-zones',
    'INAH Archaeological Zones (Mexico)',
    '494 officially open pre-Hispanic zones in Mexico (INAH / Wikidata)',
    'place',
    'circle',
    '#b5451b',
    false,
    false,
    2,
    (select id from public.sources where url = 'https://www.wikidata.org/' limit 1)
  ),
  (
    'unesco-world-heritage',
    'UNESCO World Heritage Sites',
    '50 WHC sites in Mesoamerica — UNESCO DataHub (open access)',
    'place',
    'circle',
    '#1565c0',
    false,
    false,
    3,
    (select id from public.sources where url = 'https://whc.unesco.org/en/list/' limit 1)
  ),
  (
    'lidar-surveys-opentopography',
    'Open LiDAR Surveys (OpenTopography)',
    '4 publicly archived archaeological LiDAR surveys — OpenTopography / NSF (CC-BY)',
    'place',
    'circle',
    '#7b1fa2',
    false,
    false,
    4,
    (select id from public.sources where url = 'https://opentopography.org/catalog' limit 1)
  ),
  (
    'classical-empires',
    'Classical Empires',
    'Teotihuacan, Zapotec, Maya and others (~100 BCE–900 CE)',
    'territory',
    'fill',
    '#7b2d8b',
    false,
    false,
    5,
    null
  ),
  (
    'postclassical-empires',
    'Post-Classical Empires',
    'Aztec, Tlaxcalan, Zapotec and others (~900–1521 CE)',
    'territory',
    'fill',
    '#c2185b',
    false,
    false,
    6,
    null
  ),
  (
    'maya-culture-areas',
    'Maya Culture Areas',
    '39 Maya sub-regional culture zones',
    'territory',
    'fill',
    '#2e7d32',
    false,
    false,
    7,
    null
  ),
  (
    'mayan-sites',
    'Maya Sites (ArcGIS)',
    '55 Maya sites (GIS for Humanities, San Antonio University)',
    'place',
    'circle',
    '#00838f',
    false,
    false,
    8,
    null
  ),
  (
    'aztec-villages',
    'Aztec Villages',
    '35 Aztec villages near Tenochtitlan (GIS for Humanities)',
    'place',
    'circle',
    '#e65100',
    false,
    false,
    9,
    null
  ),
  (
    'language-families',
    'Language Families',
    '26 families — Asher & Moseley 2007, Atlas of the World''s Languages (CC BY 4.0)',
    'territory',
    'fill',
    '#4527a0',
    false,
    false,
    10,
    (select id from public.sources where url = 'https://github.com/glottography/asher2007world' limit 1)
  ),
  (
    'language-dialects',
    'Language Dialects (Meso-America)',
    '99 dialect/language polygons from Map 10 — Asher & Moseley 2007, Atlas of the World''s Languages (CC BY 4.0)',
    'territory',
    'fill',
    '#4527a0',
    false,
    false,
    11,
    (select id from public.sources where url = 'https://github.com/glottography/asher2007world' limit 1)
  ),
  (
    'lidar-coverage',
    'LIDAR Survey Coverage (2019)',
    '99 LIDAR survey footprints across the Maya area, 2009–2019 (MarigisLab / MARI at Tulane University)',
    'territory',
    'fill',
    '#00bcd4',
    false,
    false,
    12,
    (select id from public.sources where url = 'https://marigis.tulane.edu/' limit 1)
  ),
  (
    'lidar-coverage-2022',
    'LIDAR Survey Coverage (2022)',
    '105 LIDAR survey footprints across the Maya area through 2022 — ancientmayasettlement.com / MARI at Tulane University',
    'territory',
    'fill',
    '#0097a7',
    false,
    false,
    13,
    (select id from public.sources where url = 'https://www.ancientmayasettlement.com/' limit 1)
  ),
  (
    'maya-settlement-groups',
    'Maya Settlement Groups (LIDAR)',
    '1,499 large & medium settlement group polygons from Tikal, Holmul, La Corona, Chactun, G-LiHT & EREDD LIDAR surveys — Estrada-Belli et al., PACUNAM / NASA G-LiHT (MarigisLab / MARI at Tulane University)',
    'place',
    'fill',
    '#ff7043',
    false,
    false,
    14,
    (select id from public.sources where url = 'https://marigis.tulane.edu/' limit 1)
  ),
  (
    'pacunam-survey-units',
    'PACUNAM LiDAR Survey Units',
    '12 PACUNAM LiDAR Initiative survey unit polygons — Estrada-Belli et al. (MarigisLab / MARI at Tulane University)',
    'territory',
    'fill',
    '#26c6da',
    false,
    false,
    15,
    (select id from public.sources where url = 'https://marigis.tulane.edu/' limit 1)
  ),
  (
    'la-milpa',
    'La Milpa Settlement, Belize',
    '~10,000 structures, berms & survey boundaries across 4 field campaigns (LMBU, Scarborough, Kunen, Robichaux) — Boston University / Tulane University La Milpa project (MarigisLab / MARI at Tulane University)',
    'place',
    'fill',
    '#ab47bc',
    false,
    false,
    16,
    (select id from public.sources where url = 'https://marigis.tulane.edu/' limit 1)
  ),
  (
    'pulltrouser-swamp',
    'Pulltrouser Swamp Settlement (Belize)',
    '525 structure polygons + 13 survey areas, Pulltrouser Swamp, Belize — ancientmayasettlement.com / MARI at Tulane University',
    'place',
    'fill',
    '#43a047',
    false,
    false,
    17,
    (select id from public.sources where url = 'https://www.ancientmayasettlement.com/' limit 1)
  ),
  (
    'pulltrouser-swamp-points',
    'Pulltrouser Swamp Structures (points)',
    '399 structure & platform points, Pulltrouser Swamp, Belize — ancientmayasettlement.com / MARI at Tulane University',
    'place',
    'circle',
    '#66bb6a',
    false,
    false,
    18,
    (select id from public.sources where url = 'https://www.ancientmayasettlement.com/' limit 1)
  ),
  (
    'becan',
    'Becan Settlement, Campeche (polygons)',
    '2,295 structure polygons + survey area & blocks, Becan, Campeche, Mexico — ancientmayasettlement.com / MARI at Tulane University',
    'place',
    'fill',
    '#f57f17',
    false,
    false,
    19,
    (select id from public.sources where url = 'https://www.ancientmayasettlement.com/' limit 1)
  ),
  (
    'becan-points',
    'Becan Structures, Campeche (points)',
    '1,270 structure & platform points, Becan, Campeche, Mexico — ancientmayasettlement.com / MARI at Tulane University',
    'place',
    'circle',
    '#ffb300',
    false,
    false,
    20,
    (select id from public.sources where url = 'https://www.ancientmayasettlement.com/' limit 1)
  ),
  (
    'volcanoes',
    'Holocene Volcanoes',
    '87 Holocene volcanoes — Smithsonian Global Volcanism Program (public domain)',
    'geo_feature',
    'circle',
    '#d32f2f',
    false,
    false,
    21,
    (select id from public.sources where url = 'https://volcano.si.edu/volcanolist_countries.cfm' limit 1)
  ),
  (
    'faults-central-america',
    'Active Faults — Central America',
    '180 fault traces with slip rates and kinematics — CCAF-DB, GEM Foundation (CC-BY 4.0)',
    'geo_feature',
    'line',
    '#b71c1c',
    false,
    false,
    22,
    (select id from public.sources where url = 'https://github.com/GEMScienceTools/gem-global-active-faults' limit 1)
  ),
  (
    'faults-mexico',
    'Active Faults — Mexico',
    '715 fault traces — GEM Global Active Faults, Mexico portion (CC-BY-SA 4.0)',
    'geo_feature',
    'line',
    '#c62828',
    false,
    false,
    23,
    (select id from public.sources where url = 'https://github.com/GEMScienceTools/gem-global-active-faults' limit 1)
  ),
  (
    'earthquakes',
    'Earthquakes (M5.0+, 1900–2024)',
    '2,000 largest M5.0+ earthquakes — USGS Earthquake Catalog (public domain)',
    'event',
    'circle',
    '#ff6f00',
    false,
    false,
    24,
    (select id from public.sources where url = 'https://earthquake.usgs.gov/earthquakes/search/' limit 1)
  ),
  (
    'major-rivers',
    'Major Rivers',
    '21,531 river segments (Strahler order ≥5) — HydroRIVERS v10, WWF / USGS HydroSHEDS (CC-BY 4.0)',
    'geo_feature',
    'line',
    '#0288d1',
    false,
    false,
    25,
    (select id from public.sources where url = 'https://www.hydrosheds.org/products/hydrorivers' limit 1)
  ),
  (
    'major-lakes',
    'Major Lakes',
    '23 major lakes — Natural Earth 10m Physical (public domain)',
    'geo_feature',
    'fill',
    '#0277bd',
    false,
    false,
    26,
    (select id from public.sources where url = 'https://www.naturalearthdata.com/downloads/10m-physical-vectors/' limit 1)
  ),
  (
    'hurricane-tracks',
    'Hurricane Tracks (1851–2023)',
    '1,614 Atlantic basin storm tracks intersecting Mesoamerica — NOAA IBTrACS v04r01 (public domain)',
    'geo_feature',
    'line',
    '#6a1b9a',
    false,
    false,
    27,
    (select id from public.sources where url = 'https://www.ncei.noaa.gov/products/international-best-track-archive' limit 1)
  ),
  (
    'coral-reefs',
    'Coral Reefs',
    '328 reef polygons in the Caribbean — OpenStreetMap (ODbL)',
    'geo_feature',
    'fill',
    '#ff6e40',
    false,
    false,
    28,
    (select id from public.sources where url = 'https://www.openstreetmap.org/' limit 1)
  ),
  (
    'ramsar-wetlands',
    'Ramsar Wetlands',
    '23 Ramsar-designated wetlands of international importance — OpenStreetMap / Ramsar Convention (ODbL)',
    'geo_feature',
    'circle',
    '#00796b',
    false,
    false,
    29,
    (select id from public.sources where url = 'https://rsis.ramsar.org/' limit 1)
  ),
  (
    'ecoregions',
    'Terrestrial Ecoregions',
    '69 ecoregions — RESOLVE Ecoregions 2017, WWF / Dinerstein et al. (CC-BY 4.0)',
    'territory',
    'fill',
    '#558b2f',
    false,
    false,
    30,
    (select id from public.sources where url = 'https://ecoregions.appspot.com/' limit 1)
  ),
  (
    'mangroves-2020',
    'Mangrove Coverage (2020)',
    '147 mangrove tile polygons — Global Mangrove Watch 2020, JAXA / Aberystwyth (CC-BY 4.0)',
    'geo_feature',
    'fill',
    '#1b5e20',
    false,
    false,
    31,
    (select id from public.sources where url = 'https://www.globalmangrovewatch.org/' limit 1)
  ),
  (
    'protected-areas',
    'Protected Areas (WDPA)',
    '2,043 protected areas — World Database on Protected Areas, UNEP-WCMC / IUCN',
    'territory',
    'fill',
    '#33691e',
    false,
    false,
    32,
    (select id from public.sources where url = 'https://www.protectedplanet.net/en' limit 1)
  ),
  (
    'culturally-significant-species',
    'Culturally Significant Species',
    '600 occurrences: Resplendent Quetzal, Jaguar — GBIF / iNaturalist (CC-BY)',
    'geo_feature',
    'circle',
    '#00c853',
    false,
    false,
    33,
    (select id from public.sources where url = 'https://www.gbif.org/' limit 1)
  ),
  (
    'conflict-events',
    'Conflict Events (2022–2023)',
    '10,781 georeferenced conflict/violence events — HDX / ACLED-sourced (CC BY-NC-SA)',
    'event',
    'circle',
    '#c62828',
    false,
    false,
    34,
    (select id from public.sources where url = 'https://data.humdata.org/' limit 1)
  ),
  (
    'admin2-boundaries',
    'Municipalities / Districts (ADM-2)',
    '3,636 municipalities & districts across 7 countries — geoBoundaries v6.0 (CC-BY 4.0)',
    'admin_boundary',
    'fill',
    '#455a64',
    false,
    false,
    35,
    (select id from public.sources where url = 'https://www.geoboundaries.org/' limit 1)
  ),
  (
    'urban-areas',
    'Urban Areas',
    '289 urban footprint polygons — Natural Earth 10m Cultural (public domain)',
    'place',
    'fill',
    '#78909c',
    false,
    false,
    36,
    (select id from public.sources where url = 'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/' limit 1)
  ),
  (
    'major-roads',
    'Major Roads',
    '329 major road segments — Natural Earth 10m Cultural (public domain)',
    'geo_feature',
    'line',
    '#546e7a',
    false,
    false,
    37,
    (select id from public.sources where url = 'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/' limit 1)
  ),
  (
    'artifacts',
    'Artifacts',
    'Excavated artifacts by location (add via form)',
    'place',
    'circle',
    '#1565c0',
    false,
    true,
    38,
    null
  );
