"""
Seeds persons and RULED relationships from Wikidata into Supabase.

Input:  scripts/wp_rulers_enriched.json  (generated by the exploration steps)
Output: entities + persons rows, relationships rows

Usage:
    python3 scripts/seed_from_wikidata.py             # insert
    python3 scripts/seed_from_wikidata.py --dry-run   # preview only
    python3 scripts/seed_from_wikidata.py --fix-rels  # backfill RULED relationships only
"""

import json
import os
import sys

import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

load_dotenv()

DB_URL  = os.environ.get('SUPABASE_DB_URL')
DRY_RUN  = '--dry-run' in sys.argv
FIX_RELS = '--fix-rels' in sys.argv
DATA_FILE = os.path.join(os.path.dirname(__file__), 'wp_rulers_enriched.json')


def fmt_year(y):
    if y is None:
        return '?'
    return f"{abs(y)} BCE" if y < 0 else f"{y} CE"


def date_label(birth, death, positions):
    if birth and death:
        return f"{fmt_year(birth)} – {fmt_year(death)}"
    rs = [p['reign_start'] for p in positions if p.get('reign_start')]
    re_ = [p['reign_end']   for p in positions if p.get('reign_end')]
    if rs or re_:
        start = fmt_year(min(rs)) if rs else '?'
        end   = fmt_year(max(re_)) if re_ else '?'
        return f"r. {start} – {end}"
    return None


def pick_city_entity(cur, city_name):
    """Return entity_id for the canonical place entity for this city name."""
    for layer in ('mayan-sites', 'sites', 'inah-archaeological-zones', 'maya-inscriptions'):
        cur.execute(
            "SELECT e.id FROM public.entities e WHERE e.name ILIKE %s AND e.layer_id = %s LIMIT 1",
            (city_name, layer)
        )
        row = cur.fetchone()
        if row:
            return row[0]
    cur.execute(
        "SELECT id FROM public.entities WHERE name ILIKE %s AND entity_type = 'place' LIMIT 1",
        (city_name,)
    )
    row = cur.fetchone()
    return row[0] if row else None


def create_ruled_relationships(cur, persons, person_index, source_id):
    inserted = 0
    no_city  = set()
    for p in persons:
        person_id = person_index.get(p['name'])
        if not person_id:
            continue
        city_id = pick_city_entity(cur, p['city'])
        if not city_id:
            no_city.add(p['city'])
            continue
        starts = [pos['reign_start'] for pos in p['positions'] if pos.get('reign_start')]
        ends   = [pos['reign_end']   for pos in p['positions'] if pos.get('reign_end')]
        cur.execute(
            "SELECT 1 FROM public.relationships WHERE from_entity_id=%s AND to_entity_id=%s AND relation_type='RULED'",
            (person_id, city_id)
        )
        if cur.fetchone():
            continue
        cur.execute(
            """INSERT INTO public.relationships
                 (from_entity_id, to_entity_id, relation_type, valid_from, valid_to, source_id)
               VALUES (%s,%s,'RULED',%s,%s,%s)""",
            (person_id, city_id,
             min(starts) if starts else None,
             max(ends)   if ends   else None,
             source_id)
        )
        inserted += 1
    if no_city:
        print(f'  No city match for: {no_city}')
    return inserted


def main():
    if not DB_URL and not DRY_RUN:
        sys.exit('ERROR: SUPABASE_DB_URL not set')

    with open(DATA_FILE) as f:
        persons = json.load(f)

    if FIX_RELS:
        conn = psycopg2.connect(DB_URL)
        with conn.cursor() as cur:
            cur.execute("SELECT id FROM public.sources WHERE url = 'https://www.wikidata.org'")
            source_id = cur.fetchone()[0]
            cur.execute("SELECT name, id FROM public.entities WHERE entity_type = 'person' AND source_id = %s", (source_id,))
            person_index = {row[0]: row[1] for row in cur.fetchall()}
            n = create_ruled_relationships(cur, persons, person_index, source_id)
        conn.commit()
        conn.close()
        print(f'Created {n} RULED relationships')
        return

    if DRY_RUN:
        print(f'[DRY RUN] {len(persons)} persons to consider\n')
        for p in persons[:15]:
            dl = date_label(p['birth'], p['death'], p['positions'])
            print(f"  {p['name']:<45} [{p['city']:<18}] {dl or '(no dates)'}")
        print(f'\n  ...and {max(0, len(persons)-15)} more')
        return

    conn = psycopg2.connect(DB_URL)

    with conn.cursor() as cur:
        # Ensure Wikidata source exists
        cur.execute("SELECT id FROM public.sources WHERE url = 'https://www.wikidata.org'")
        row = cur.fetchone()
        if row:
            source_id = row[0]
        else:
            cur.execute(
                """INSERT INTO public.sources (name, source_type, url, description, license)
                   VALUES (%s,%s,%s,%s,%s) RETURNING id""",
                ('Wikidata', 'dataset', 'https://www.wikidata.org',
                 'Wikidata — structured data from the Wikimedia Foundation', 'CC0')
            )
            source_id = cur.fetchone()[0]
        print(f'Wikidata source_id: {source_id}')

        # Index existing persons by name (avoid duplicates on re-run)
        cur.execute("SELECT name, id FROM public.entities WHERE entity_type = 'person'")
        existing = {row[0]: row[1] for row in cur.fetchall()}
        print(f'Existing person entities: {len(existing)}')

        inserted_persons = 0
        inserted_rels    = 0
        skipped          = 0

        for p in persons:
            name = p['name']

            if name in existing:
                skipped += 1
                continue

            birth     = p.get('birth')
            death     = p.get('death')
            positions = p.get('positions', [])
            dl        = date_label(birth, death, positions)

            # Floruit from reign dates when birth/death unknown
            floruit_start = None
            floruit_end   = None
            if not birth:
                starts = [pos['reign_start'] for pos in positions if pos.get('reign_start')]
                if starts:
                    floruit_start = min(starts)
            if not death:
                ends = [pos['reign_end'] for pos in positions if pos.get('reign_end')]
                if ends:
                    floruit_end = max(ends)

            precision = 'approximate' if (birth or floruit_start) else 'unknown'

            # Insert entity
            cur.execute(
                "INSERT INTO public.entities (entity_type, name, source_id) VALUES ('person',%s,%s) RETURNING id",
                (name, source_id)
            )
            entity_id = cur.fetchone()[0]

            # Insert persons extension
            cur.execute(
                """INSERT INTO public.persons
                     (entity_id, person_type, birth_year, death_year,
                      floruit_start, floruit_end, date_precision, date_label)
                   VALUES (%s,'ruler',%s,%s,%s,%s,%s,%s)""",
                (entity_id, birth, death, floruit_start, floruit_end, precision, dl)
            )

            inserted_persons += 1
            existing[name] = entity_id

            # RULED relationship via pick_city_entity (prefers curated layers)
            city_id = pick_city_entity(cur, p['city'])
            if city_id:
                all_starts = [pos['reign_start'] for pos in positions if pos.get('reign_start')]
                all_ends   = [pos['reign_end']   for pos in positions if pos.get('reign_end')]
                cur.execute(
                    """INSERT INTO public.relationships
                         (from_entity_id, to_entity_id, relation_type,
                          valid_from, valid_to, source_id)
                       VALUES (%s,%s,'RULED',%s,%s,%s)""",
                    (entity_id, city_id,
                     min(all_starts) if all_starts else None,
                     max(all_ends)   if all_ends   else None,
                     source_id)
                )
                inserted_rels += 1

        conn.commit()

    conn.close()
    print(f'\nInserted: {inserted_persons} persons, {inserted_rels} RULED relationships')
    print(f'Skipped (already existed): {skipped}')


if __name__ == '__main__':
    main()
